### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by nauticas** [nauticas/how-to-git#1]
menjelasakan cara kerja git
-- tuliskan dengan nama file readme-git-flow.md

**Comment by d8920ya** [comment]
Issue ini sudah saya update dan dapat dicek pada branch [[Git-Workflow]](https://github.com/nauticas/how-to-git/tree/Git-Workflow) .
Hasil sudah dicoba membuat `pull request` dan saya `merge` . 
Issue ini akan saya `close` . Terima kasih .
